version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - GITLAB_CLIENT_ID=${GITLAB_CLIENT_ID}
      - GITLAB_SECRET=${GITLAB_SECRET}
      - GITLAB_REDIRECT_URI=${GITLAB_REDIRECT_URI}
      - SESSION_SECRET=${SESSION_SECRET}
    volumes:
      - ./scenarios:/app/scenarios
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
